# Developer IDs
developers:
  - 1803044735

# Custom messages
customMessages:
  prohibitedLinks: "Maaf {{user}}, tautan tersebut berada dalam daftar hitam"
  prohibitedWords: "Maaf {{user}}, kata dalam pesan yang anda kirim terdapat kata terlarang"
  groupPromotion: "Maaf {{user}}, promosi dalam grup ini tidak diperbolehkan ya"

# Features on/off
features:
  # To disable, just set the prohibitedLinks.enabled to false
  prohibitedLinks:
    enabled: true
    sendToGroup: false
    action: delete # available: ignore, delete, kick
    links:
      - t.me
      - /(*\.domain\.com)/gi

  # To disable, just set the prohibitedWors.enabled to false
  prohibitedWords:
    enabled: true
    sendToGroup: false
    action: delete # available: ignore, delete, kick
    words:
      - this-is-badword
  
  # Filter group promotions (by @tag, and links)
  # To disable, just set the noGroupPromotions.enabled to false
  noGroupPromotions:
    # Enabled status
    enabled: true
    # By tags
    tags: true
    # By links
    links: true

    # Message, set it to false if you won't send message to the group
    messageEnabled: true

    # Action
    action: delete # available: delete, ignore, kick
    
    # Bypass hastag (#hastag)
    bypassHastags:
      - sharegroup

# applied groups config (without setup)
appliedGroupsConfig:
  - 00000000