/**
 * Copyright (c) 2022 - Nayaka Project
 * FILE INI ADALAH BAGIAN DARI NAYAKA PROJECT.
 * Nayaka merupakan Open Source Software dengan Apache License V2.
 * Anda dapat mengedit atau mendistribusikan ulang sesuai dengan syarat dan ketentuan dari Apache License.
 */
// GENERATED BY: github.com/hansputera-lab/graphql-to-ts

export interface ProhibitedWord {
	patterns?: string[];
	patternFlag?: string;
	words?: string[];
	caseSensitive?: boolean;
	group: Group;
}
export interface ProhibitedLink {
	patterns?: string[];
	patternFlag?: string;
	cleanUrls?: string[];
	group: Group;
}
export enum GroupSettingAction {
	Delete,
	Ignore,
	Kick,
}
export interface GroupSetting {
	enabled: boolean;
	sendToGroup: boolean;
	action: GroupSettingAction;
}
export interface GroupPromotionSetting {
	enabled: boolean;
	sendToGroup: boolean;
	action: GroupSettingAction;
	byTags: boolean;
	byLinks: boolean;
	bypassHastag: string[];
}
export interface GroupSettings {
	prohibitedLinks: GroupSetting;
	prohibitedWords: GroupSetting;
	promotion: GroupPromotionSetting;
	group: Group;
}
export interface Group {
	id: string;
	settings: GroupSettings;
	links?: ProhibitedLink[];
	words?: ProhibitedWord[];
}
